---
driver:
  name: docker

provisioner:
  hosts: all
  name: ansible_playbook
#  require_ansible_omnibus: false # No need ansible on this container
#  require_ansible_source: false # No need ansible on this container
#  require_ansible_repo: false # No need ansible on this container
  require_ruby_for_busser: true # see note [1]
  ansible_verbosity: 2
  ansible_verbose: true

verifier:
  name: busser
  plugin:
  - Ansiblespec
  ruby_bindir: '/usr/bin'
platforms:
 - name: ubuntu-18.04

suites:
 - name: default

